#docker-compose -f docker-compose.redis.yml -p redis_layer_test1 up -d --build



services:
  redis:
    image: redis:latest
    container_name: ${DOMAIN_NAME}_redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - shared_network  # 서비스 레이어와 동일한 네트워크 사용
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: always

networks:
  shared_network:
    external: true  # 동일한 네트워크를 사용하여 다른 서비스들과 통신 가능
